use updated hab inspec integration
Signed-off-by: Nell Shamrell <nellshamrell@gmail.com>

diff --git a/habitat/hooks/run b/habitat/hooks/run
--- a/habitat/hooks/run
+++ b/habitat/hooks/run
@@ -1,36 +1,36 @@
-#!/bin/sh
+#!{{pkgPathFor "core/bash"}}/bin/bash
 
-# redirect stderr to stdout
-# ultimately, we'd like to log this somewhere useful, but due to
-# https://github.com/habitat-sh/habitat/issues/2395, we need to
-# avoid doing that for now.
+# Redirect stderr to stdout
+# This will be captured by Habitat and viewable via `journalctl`
+# NOTE: We might want log to "{{pkg.svc_path}}/logs" and handle rotation
 exec 2>&1
 
 # InSpec will try to create a .cache directory in the user's home directory
 # so this needs to be someplace writeable by the hab user
 export HOME={{pkg.svc_var_path}}
 
-PROFILE_IDENT="{{pkg.origin}}/{{pkg.name}}"
 RESULTS_DIR="{{pkg.svc_var_path}}/inspec_results"
 RESULTS_FILE="${RESULTS_DIR}/{{pkg.name}}.json"
 
-# Create a directory for inspec formatter output
-mkdir -p {{pkg.svc_var_path}}/inspec_results
+# Create a directory for InSpec reporter output
+mkdir -p $(dirname $RESULTS_FILE)
 
 while true; do
-  echo "Executing InSpec for ${PROFILE_IDENT}"
-  inspec exec {{pkg.path}}/dist --format=json > ${RESULTS_FILE}
+  echo "Executing InSpec for {{pkg.ident}}"
+  inspec exec "{{pkg.path}}/profiles/*" --reporter=json > ${RESULTS_FILE}
 
-  if [ $? -eq 0 ]; then
+  EXIT_STATUS=$?
+  if [ $EXIT_STATUS -eq 0 ]; then
     echo "InSpec run completed successfully."
+  elif [ $EXIT_STATUS -eq 100 ]; then
+    echo "InSpec run completed successfully, with at least 1 failed test"
+  elif [ $EXIT_STATUS -eq 101 ]; then
+    echo "InSpec run completed successfully, with skipped tests and no failures"
   else
-    echo "InSpec run did not complete successfully. If you do not see any errors above,"
-    echo "control failures were detected. Check the InSpec results here for details:"
-    echo ${RESULTS_FILE}
-    echo "Otherwise, troubleshoot any errors shown above."
+    echo "InSpec run did not complete successfully. Exited with status: $?"
   fi
+  echo "Results located here: ${RESULTS_FILE}"
 
-  source {{pkg.svc_config_path}}/settings.sh
-  echo "sleeping for ${SLEEP_TIME} seconds"
-  sleep ${SLEEP_TIME}
+  echo "Sleeping for {{cfg.sleep_time}} seconds"
+  sleep {{cfg.sleep_time}}
 done
